# Use an official TensorFlow runtime as a parent image
FROM python:3.8-slim


# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Install any needed packages specified in requirements.txt
RUN pip install numpy flask tensorflow Pillow

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variables
ENV MODEL_PATH=/app/test_model.h5
ENV TOKENIZER_PATH=/app/tokenizer.pkl

# Run app.py when the container launches
CMD ["python", "image_captioning_server.py"]