using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WebAppBachelorProject.Areas.Identity.Data;

namespace WebAppBachelorProject.Models
{

    /// <summary>
    /// Image entity in the DB. Providing details about the image.
    /// Has relationship with a user and metadata properties like creation date, description and evaluation. 
    /// </summary>
    public class Image
    {

        //Unique key identifier for the image. Automatically generated by the database. 
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string ImageId { get; set; }


        //Description of the image. 
        public string Description { get; set; }

        //Where the image is saved.
        [Required]
        public string ImagePath { get; set; }

        //User ID associated with this image. This forms a one-to-many relationship between ApplicationUser and Image.
        [Required]
        public string UserId { get; set; }

        // Gets or sets the date and time when the image was uploaded/created in DB.
        public DateTime DateCreated { get; set; }

        //Evaluation of the image.
        public string Evaluation {  get; set; }


        //Navigation property for the ApplicationUser that owns this Image.
        public WebAppBachelorProjectUser User { get; set; }
    }
}
